config/routes.rb
Rails.application.routes.draw do
  # get 'reviews/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    resources :reviews, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validate :phone_number_format

  def phone_number_format
    # puts 'valid'
    if phone_number.blank?
      errors.add(:phone_number, 'must be a valid French phone number')
      return false
    end

    phone = ''
    phone_number.chars.each { |c| phone << c if c != ' ' }
    check = phone.match(/\A(0|\+33)[1-9]\d{8}\z/) ? true : false
    if !phone_number.present? || !check
      errors.add(:phone_number, 'must be a valid French phone number')
      return false
    end
    true
  end

  validates :category, inclusion: { in: %w[chinese italian japanese french belgian],
                                    message: '%<value>s is not a valid category' }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true,
                      numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.valid?
      @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<div class="container">
  <h1>Update Restaurant</h1>
  <div class="m-5">
    <%= simple_form_for(@restaurant) do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :phone_number %>
      <%= f.input :category, collection: %w[chinese italian japanese french belgian], include_blank: true %>
      <%= f.submit %>
    <% end %>
  </div>
  <%= link_to 'Back to list restaurants', restaurants_path %>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Restaurants</h1>
  <div class="restaurants">
    <% @restaurants.each do |restaurant|  %>
      <div class="card mt-2" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"> <%= link_to restaurant.name, restaurant_path(restaurant) %> </h5>
          <p class="card-text"> <%= restaurant.address %> </p>
          <p>Téléphone: <%= restaurant.phone_number %> </p>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to "Add new restaurant", new_restaurant_path %>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>New Restaurant</h1>
  <div class="mt-3">
    <%= simple_form_for(@restaurant) do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :phone_number %>
      <%= f.input :category, collection: %w[chinese italian japanese french belgian], include_blank: true %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1><%= @restaurant.name %></h1>
  <p><%= @restaurant.address %></p>
  <p><%= @restaurant.phone_number %></p>
  <p><%= @restaurant.category %></p>
  <%= link_to 'All review', restaurant_reviews_path(@restaurant) %>
  <%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
  <%= link_to 'Back to list Restaurant', restaurants_path %> |
  <%= link_to 'Delete', restaurant_path(@restaurant), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</div>

app/views/reviews/index.html.erb
<div class="container">
  <h1>Review <%= @restaurant.name %></h1>
  <ul class="list-group">
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item">
        <p><%= review.content %></p>
        <p>Rating: <%= review.rating %>/5</p>
      </li>
    <% end %>
  </ul>
  <%= link_to 'Get back to restaurant', restaurant_path(@restaurant) %> |
  <%= link_to 'Create new review', new_restaurant_review_path %>
</div>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= simple_form_for [@restaurant, @review], url: restaurant_reviews_path(@restaurant) do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
  <%= link_to 'get back to restaurant', restaurant_path(@restaurant) %>
<% end %>